pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/Nandiniii4/college-projects.git'
            }
        }

        stage('Linting') {
            steps {
                echo 'Checking HTML, CSS, and JavaScript files in project1...'
                sh 'npx html-validate project1/index.html'
                sh 'npx stylelint "project1/**/*.css" || true'
                sh 'npx eslint "project1/**/*.js" || true'
            }
        }

        stage('Testing') {
            steps {
                echo 'Running JavaScript tests (if any) for project1...'
                sh 'cd project1 && npm install && npm test'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying project1...'
                sh 'rsync -avz project1 /var/www/html/project1'
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful!'
        }
        failure {
            echo 'Pipeline Failed!'
        }
    }
}
